### ISSUE TITLE
Co-worker email invite

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#141]
Add the ability to invite fellow teachers to the school using email.

### TODO

- [x] Create an endpoint for sending invites.
    - Maybe on `/school/{schoolId}invite-user`
    - Accepts a list of email address
    - Sends email to all email address

- [ ] Add new page for sending invites on frontend.

### Example UI
![image](https://user-images.githubusercontent.com/8491552/87515021-5ff4be80-c6a5-11ea-8eae-882699373d47.png)

**Comment by christianto88** [comment]
What is the usage of 'inviteCode' field in school?

**Comment by chrsep** [comment]
> @chrsep What is the usage of 'inviteCode' field in school?

Thats for inviting user to join a school. An invite code is owned by a school, when a user register with an invite code, they’’ll be given access to the school who own the invite code.

**Comment by christianto88** [comment]
@chrsep So every invite email that we sent, must contain an invite code. Then when user register, they need to input the invite code?

**Comment by chrsep** [comment]
We can attach it to the registration url. Such as ‘https://obserfy.com/register?inviteCode={theinvitecode}’. The registration page will handle the rest.

The settings page already displays this links actually, so users can send it manually. There is also an api that generates this url if I’m not mistaken, gotta check first.

**Comment by christianto88** [comment]
@chrsep Yes thats what im thinking of. Then the registration page will need to extract the "inviteCode" query string and use that as input for auth/register route

**Comment by chrsep** [comment]
Yes, here is where the settings page get the invite link. https://github.com/obserfy/vor/blob/a07b1839c80dc688e35e8a90161985adb64a4360/pkg/school/school.go#L218-L223

**Comment by christianto88** [comment]
@chrsep Yea i mean is there already a handler to extract that 'inviteCode' query string on register's page button click?

**Comment by chrsep** [comment]
Yes, we have that already. It's done on react.
https://github.com/obserfy/vor/blob/3e426e3944b88e75ee45c197f12d40c8e9f32353/frontend/src/pages/register.tsx#L8-L14

**Comment by chrsep** [comment]
The register page will automatically include the invite code when to user submits the form, if it can find the inviteCode on the query string.

**Comment by christianto88** [comment]
@chrsep okay nice
