### ISSUE TITLE
Localize landing page to indonesia.

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#363]
Implement i18n on the landing page. We should first target localization to Indonesia.

**Comment by zeirash** [comment]
what tools we will use to implement the localization?

**Comment by chrsep** [comment]
I don't know yet 😂. I was planning to use lingui, but v3 (which is still in beta) as I understand would be quite a breaking changes, existing gatsby plugin still uses v2. I tried to build a plugin for v3 on [chrsep/gatsby-plugin-lingui3](https://github.com/chrsep/gatsby-plugin-lingui3), it is still half-finished though.

Also, Gatsby's documentation website ditched lingui in favour of separating the website into multiple standalone ones. [More info here](https://gist.github.com/tesseralis/f7f5f7da2f7f6cf5c2fa6ee715b5ff6d).

Official i18n support is on gatsby's roadmap though, it might be better for us to wait for that. There are problems with build time and localization chunking that are still being discussed. Since i18n is not really high on our priorities right now I think we could afford to wait until a proper solution emerged.

**Comment by chrsep** [comment]
Blocked, waiting for gatsby-theme-i18n-lingui alpha version to be released.

**Comment by zeirash** [comment]
not blocked anymore. gatsby plugin support for !18n already released

**Comment by chrsep** [comment]
fixed by #814
