### ISSUE TITLE
Allow setting observation's event time.

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#671]
Currently, we have a column called event time in observation table. This is used to indicate when the event related to an observation happens (ex. Michael learns math on 12th May). Currently, this event time cannet be set from the API and UI. Which means that the UI and API need to be updated.

#### API
- [x] Update `POST` observation API to accept event time
- [x] Update `GET` observation dialog to also return event time
#### UI
- [x] Add event time selector to new observation page, defaulting to current time
- [x] Add event time selector to edit observation dialog
- [x] Copy over created_date values to event_time on prod to provide default value instead of being null
- [x] Update Observation page to use event time instead of created_date
- [x] Update observation list in student overview to use event time instead of created_date

**Comment by christianto88** [comment]
Could you please add some description? @chrsep

**Comment by chrsep** [comment]
@christianto88 Updated

**Comment by chrsep** [comment]
closed by #138
