### ISSUE TITLE
Add ability to edit student's profile picture

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#777]
### Summary
Currently, we can only set the student's profile picture when we create them. A simple way to allow teachers to set student's profile images would be to just add a "Set as profile" button in PageStudentImageDetails.

### To-do
- [ ] Update patch student API to accept patching the new ProfileImageId
- [ ] Update usePatchStudentApi hook to accept the new parameter
- [x] Add button

**Comment by zeirash** [comment]
i will take this one. is there any rough sketch or something?

**Comment by chrsep** [comment]
I was thinking of just adding a "set as profile picture" button in PageStudentImageDetails.

**Comment by chrsep** [comment]
![image](https://user-images.githubusercontent.com/8491552/92971128-16a8cb80-f4aa-11ea-9c36-3bd5e6ae0e47.png)

**Comment by chrsep** [comment]
I think we could simply use the patch student API in students.go, it just needs a bit modification to accept updating ProfileImageId. The `usePatchStudentApi` hook on the frontend would also need to be updated accordingly. I'll add to the description.

**Comment by zeirash** [comment]
is `PageStudentImageDetails` a new component?

**Comment by chrsep** [comment]
No, it already exists. We, just need to add the button.

**Comment by chrsep** [comment]
closed on #997
