### ISSUE TITLE
Add ability to remove a user from a school.

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#800]
Deleting user should only delete its relationship with the related school, nothing else.

#### Todo
- [x] add `DELETE` `/school/{schoolId}/users/{userId}`
- [x] add remove button to list of users

#### Example
![image](https://user-images.githubusercontent.com/8491552/89524819-6c38eb00-d80f-11ea-975b-fb92e93d99dd.png)

**Comment by christianto88** [comment]
@chrsep is the UserDetails page a new page?

**Comment by chrsep** [comment]
Yes, that is a new page.

**Comment by christianto88** [comment]
So this function will just delete the relationship between a user and the school which is from table userToSchool. 
Let say we have school A and user A. We delete the relationship between them, and school A doesn't have any users. It becomes an 'orphan' school. Is there any way to assign user to school A?

**Comment by chrsep** [comment]
Yeah, we don't have any of that. If every user is removed then the school will become an orphan forever. I guess we can generate an invite link manually if any users try to ask us.

I guess we can avoid this by only allowing users to remove other users on the UI, not themself? I've updated the description with a screenshot.

**Comment by christianto88** [comment]
@chrsep From UI standpoint, we use the existing "Users Page" UI and add remove button. And also, user is not able to remove himself

**Comment by chrsep** [comment]
yes, that's the gist of it.

**Comment by christianto88** [comment]
Can we close this now? @chrsep

**Comment by chrsep** [comment]
Yes, ill close it
