### ISSUE TITLE
Add auth middleware for lesson plan API

### ISSUE THREAD

**Issue by chrsep** [obserfy/obserfy#801]

**Comment by christianto88** [comment]
What should we restrict here @chrsep ?

**Comment by chrsep** [comment]
Similar to other routes. Only users with a relation to the school related to the lesson plan can edit/delete the lesson plan.

**Comment by christianto88** [comment]
@chrsep On lessonPlanDetails, we have userId which represent that the lessonPlan created by a user. 
Which one is correct ? 
A. User should only access( get,edit,delete) lesson plan that is created by the user itself
B. User can access ( get,edit,delete) other lesson plan created by other user as long as they are in the same school

**Comment by chrsep** [comment]
B. As long as they are in the same school it should be fine.
